spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:http://config-server:8071"
    # RabbitMQ, cloud bus 설정
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,busrefresh