spring:
  application:
    name: config-server
  profiles:
    active:
      - git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LGCoreNova/Config.git
          default-label: feat-cloudbus
          search-paths:
            - article
            - auth
            - board
            - eureka
            - gateway
    bus:
      enabled: true
      refresh:
        enabled: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8071

encrypt:
  key: WeAreTestOurProjectSoHappyUmmReally

management:
  endpoints:
    web:
      exposure:
        include: "health,info,busrefresh"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true

